import { Component } from '@angular/core';
import { Button } from 'primeng/button';
import { Vehicle } from '../../models/vehicle';
import { VehicleServiceService } from '../../services/vehicle-service.service';
import { Location } from '../../models/location';
import { LocationService } from '../../services/location.service';
import { RentalService } from '../../services/rental.service';
import { RentOuts } from '../../models/rent-outs';
import { CommonModule } from '@angular/common';
import { TableModule } from 'primeng/table';
import { InputTextModule } from 'primeng/inputtext';
import { FormsModule } from '@angular/forms';
import { FloatLabel } from 'primeng/floatlabel';
@Component({
  selector: 'app-rental-return-card',
  imports: [ Button, [CommonModule], TableModule, InputTextModule, FormsModule, FloatLabel],
  templateUrl: './rental-return-card.component.html',
  styleUrl: './rental-return-card.component.scss',
})
export class RentalReturnCardComponent {
  locations: Location[] = [];
  locatedRental: RentOuts | null = null; // Store the located car details
  locatedCar: Vehicle | null = null;  
  pickupLocation: Location | null = null; // Store the pickup location details
  dropoffLocation: Location | null = null; // Store the dropoff location details

  
  constructor(
    private vehicleServiceService: VehicleServiceService,
    private locationService: LocationService,
    private rentalService: RentalService
  ) {}


  // Rental Variables
  rental_id: number | null = null;
  start_mileage: number | null = null;
  return_mileage: number | null = null;
  start_date: string = '2025-01-15';
  return_date: string = '2025-01-15';
  VIN: string = '';
  user_id: number | null = null
  pickup_location_id: number | null = null;
  dropoff_location_id: number | null = null;
  payment_id: number | null = null;


  ngOnInit(): void {
    this.locateRental();
  }

  locateRental(): void {
    this.rentalService.locateRental(0).subscribe(
      (rentalResponse) => {
        this.locatedRental = rentalResponse; // Store the located rental details

        if (this.locatedRental && this.locatedRental.VIN) {
          // Fetch the car details using the VIN from the located rental
          this.vehicleServiceService.locateCar(this.locatedRental.VIN).subscribe(
            (carResponse) => {
              this.locatedCar = carResponse; // Store the located car details
              console.log('Located Car:', this.locatedCar);
            },
            (carError) => {
              console.error('Error locating car by VIN:', carError);
            }
          );
        }
      },
      (rentalError) => {
        console.error('Error locating rental:', rentalError);
      }
    );
  }

  // Reserve the car
  returnCar(): void {
     if (!this.return_mileage) {
      alert('Please enter return milage to complete drop-off');
      return;
    }
    if (this.locatedRental! !== null) {
    
 
    // Create the rent-out object
    const rentOut: RentOuts = {
      rental_id: this.locatedRental.rental_id, // Auto-generated by the backend
      start_mileage: this.locatedRental.start_mileage,
      return_mileage: this.return_mileage!, 
      start_date: this.locatedRental.start_date, // Current date
      return_date: this.locatedRental.return_date, 
      VIN: this.locatedRental.VIN,
      user_id: this.locatedRental.user_id,
      pickup_location_id: this.locatedRental.pickup_location_id,
      dropoff_location_id: this.locatedRental.dropoff_location_id,
      payment_id: this.locatedRental.payment_id,
    };

    
      // Call the addRental() method to create the rent-out
    this.rentalService.updateRental(rentOut).subscribe(
      (response) => {
        console.log('Car reserved successfully:', response);
        alert('Car Dropped Off');
      },
      (error) => {
        console.error('Error reserving car:', error);
        alert('Failed to complete drop off car, please check info');
      }
    );
    }
  }

}
