import { Component } from '@angular/core';
import { AccordionModule } from 'primeng/accordion';
import { InputTextModule } from 'primeng/inputtext';
import { FloatLabelModule } from 'primeng/floatlabel';
import { FormsModule } from '@angular/forms';
import { SelectModule } from 'primeng/select';
import { VehicleServiceService } from '../../services/vehicle-service.service';
import { CommonModule } from '@angular/common';
import { Location } from '../../models/location';
import { LocationService } from '../../services/location.service';
import { Button } from "primeng/button";

@Component({
  selector: 'app-register-info',
  imports: [AccordionModule, InputTextModule, FloatLabelModule, FormsModule, SelectModule, [CommonModule], Button],
  templateUrl: './register-info.component.html',
  styleUrl: './register-info.component.scss',
})
export class RegisterInfoComponent {

  car_status_list = [
    { label: 'Available', value: 'available' },
    { label: 'Unavailable', value: 'unavailable' },
    { label: 'Under Maintenance', value: 'under_maintenance' }
  ];
  vin: string = '';
  license_plate: string = '';
  year: number | null = null;
  make: string = '';
  model: string = '';
  body_style: string = '';
  color: string = '';
  miles: number | null = null;
  rental_price: number | null = null;
  location_id: number | null = null;
  fuel_type: string = '';
  rental_status: any = '';
  photo_url: string = '';

  locatedCar: any = null; // Store the located car details

  // Properties for adding a new location
  locationName: string = '';
  addressLine1: string = '';
  addressLine2: string = '';
  city: string = '';
  state: string = '';
  zipCode: number | null = null;
  country: string = '';
  phoneNumber: string = '';
  constructor(
      private VehicleServiceService: VehicleServiceService,
      private LocationService: LocationService
    ) {}

  // Add a new car
  addCar(): void {
    const car = {
      VIN: this.vin,
      license_plate: this.license_plate,
      year: this.year,
      make: this.make,
      model: this.model,
      body_style: this.body_style,
      color: this.color,
      miles: this.miles,
      rental_price: this.rental_price,
      location_id: this.location_id,
      fuel_type: this.fuel_type,
      rental_status: this.rental_status,
      photo_url: this.photo_url,
    };

    this.VehicleServiceService.addCar(car).subscribe(
      (response) => {
        console.log('Car added successfully:', response);
        alert('Car added successfully!');
      },
      (error) => {
        console.error('Error adding car:', error);
        alert('Failed to add car.');
      }
    );
  }

  // Delete a car by VIN
  deleteCar(vin: string): void {
    this.VehicleServiceService.deleteCar(vin).subscribe(
      (response) => {
        console.log('Car deleted successfully:', response);
      },
      (error) => {
        console.error('Error deleting car:', error);
      }
    );
  }

  locateCar(): void {
    if (!this.vin) {
      alert('Please enter a VIN to locate the car.');
      return;
    }

    this.VehicleServiceService.locateCar(this.vin).subscribe(
      (response) => {
        this.locatedCar = response; // Store the located car details
      },
      (error) => {
        console.error('Error locating car:', error);
        alert('Failed to locate car. Please check the VIN and try again.');
      }
    );
  }
  // Add a new location
  addLocation(): void {
    const newLocation: Location = {
      location_id: 0, // This will be auto-generated by the backend
      Lname: this.locationName,
      address_line1: this.addressLine1,
      address_line2: this.addressLine2,
      city: this.city,
      state: this.state,
      zip_code: this.zipCode || 0,
      country: this.country,
      phone_number: this.phoneNumber,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };

    this.LocationService.addLocation(newLocation).subscribe(
      (response) => {
        console.log('Location added successfully:', response);
        alert('Location added successfully!');
        // Reset the form fields
        this.locationName = '';
        this.addressLine1 = '';
        this.addressLine2 = '';
        this.city = '';
        this.state = '';
        this.zipCode = null;
        this.country = '';
        this.phoneNumber = '';
      },
      (error) => {
        console.error('Error adding location:', error);
        alert('Failed to add location.');
      }
    );
  }
}
