import { Component, Input, Output, EventEmitter} from '@angular/core';
import { Button } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { UserService } from '../../services/user.service';
import { User } from '../../models/users';
import { RouterLink } from "@angular/router";
import { RentOuts } from '../../models/rent-outs';
import { RentalService } from '../../services/rental.service';
import { PaymentInfo } from '../../models/payment-info';
import { PaymentService } from '../../services/payment.service';
@Component({
  selector: 'app-reserve-car',
  imports: [Button, DialogModule, RouterLink],
  templateUrl: './reserve-car.component.html',
  styleUrl: './reserve-car.component.scss',
})
export class ReserveCarComponent {
  @Input() carData: any; 
  @Output() closeDialog = new EventEmitter<void>(); // Event emitter to notify parent component

  visible: boolean = true; // Controls the visibility of the dialog
  paymentInfo: PaymentInfo | null = null; // Stores the user's payment info

  loggedInUser: User | null = null;

  constructor(
    private rentalService: RentalService,
    private userService: UserService,
    private paymentService: PaymentService
  ) {}


  ngOnInit(): void {
    // Subscribe to the logged-in user observable
    this.userService.loggedInUser$.subscribe((user) => {
      this.loggedInUser = user;

      // Fetch payment info only if the user is logged in
      if (this.loggedInUser) {
        this.paymentService.getPaymentInfo(this.loggedInUser.user_id).subscribe(
          (paymentInfo) => {
            if (paymentInfo) {
              this.paymentInfo = paymentInfo; // Assign the fetched payment info
            } else {
              this.paymentInfo = null; // No payment info found
            }
          },
          (error) => {
            console.error('Error fetching payment info:', error);
            this.paymentInfo = null;
          }
        );
      }
    });
  }


  showDialog(): void {
    this.visible = true;
  }
  // Method to hide the dialog (optional, can also use inline binding)
  hideDialog(): void {
    this.visible = false;
  }

  // Reserve the car
  reserveCar(): void {
    if (!this.carData || !this.loggedInUser) {
      alert('Car data or user data is missing!');
      return;
    }

    // Ensure payment info exists (use a local const so TypeScript can narrow the type)
    const paymentInfo = this.paymentInfo;
    if (!paymentInfo) {
      alert('No payment information on file. Please add payment info before reserving.');
      return;
    }

    // Create the rent-out object
    const rentOut: RentOuts = {
      rental_id: 0, // Auto-generated by the backend
      start_mileage: this.carData.miles,
      return_mileage: 0, // Set to 0 initially
      start_date: '2025-07-05', // Current date
      return_date: '2025-07-05', // To be set later
      VIN: this.carData.VIN,
      user_id: this.loggedInUser.user_id,
      pickup_location_id: this.carData.location_id,
      dropoff_location_id: this.carData.location_id,
      payment_id: paymentInfo.payment_id,
    };
    
    // Call the addRental() method to create the rent-out
    this.rentalService.addRental(rentOut).subscribe(
      (response) => {
        console.log('Car reserved successfully:', response);
        alert('Car reserved successfully!');
        this.visible = false; // Close the dialog
      },
      (error) => {
        console.error('Error reserving car:', error);
        alert('Failed to reserve the car. Please try again.');
      }
    );
  }
  
  close(): void {
    this.visible = false;
    this.closeDialog.emit(); // Notify the parent component
  }
    
}
