import { Component, Input, Output, EventEmitter} from '@angular/core';
import { Button } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { UserService } from '../../services/user.service';
import { User } from '../../models/users';
import { RouterLink } from "@angular/router";
import { RentOuts } from '../../models/rent-outs';
import { RentalService } from '../../services/rental.service';
import { PaymentInfo } from '../../models/payment-info';
import { PaymentService } from '../../services/payment.service';
import { ToastModule } from 'primeng/toast';
import { FloatLabel } from 'primeng/floatlabel';
import { InputTextModule } from 'primeng/inputtext';
import { FormsModule } from '@angular/forms';
@Component({
  selector: 'app-reserve-car',
  imports: [Button, DialogModule, RouterLink, ToastModule, FloatLabel, InputTextModule, FormsModule],
  templateUrl: './reserve-car.component.html',
  styleUrl: './reserve-car.component.scss',
})
export class ReserveCarComponent {
  @Input() carData: any; 
  @Output() closeDialog = new EventEmitter<void>(); // Event emitter to notify parent component
  @Input() pickUpLocationId: number | null = null; // The selected pick-up location
  @Input() dropOffLocationId: number | null = null; // The selected drop-off location
  @Input() dates: Date[] = []; // The selected drop-off location
  visible: boolean = true; // Controls the visibility of the dialog
  paymentInfo: PaymentInfo | null = null; // Stores the user's payment info
  loggedInUser: User | null = null;

  constructor(
    private rentalService: RentalService,
    private userService: UserService,
    private paymentService: PaymentService
  ) {}

  // Payment information variables
  payment_id: number = 0;
  cardholder_name: string = '';
  card_number: string = '';
  exp_month: number | null = null;
  exp_year: number | null = null;
  cvv: string = '';
  billing_address: string = '';
  city: string = '';
  state: string = '';
  zip_code: string = '';
  country: string = '';
  user_id: number | null = null;

  addCard(): void {
      const newCard: PaymentInfo = {
        payment_id: 0,
        cardholder_name: this.cardholder_name,
        card_number: this.card_number,
        exp_month: this.exp_month!,
        exp_year: this.exp_year!,
        cvv: this.cvv,
        billing_address: this.billing_address,
        city: this.city,
        state: this.state,
        zip_code: this.zip_code,
        country: this.country,
        user_id: this.user_id!
      };
  
      this.paymentService.createPaymentInfo(newCard).subscribe(
        (response) => {
          console.log('Payment added successfully:', response);
          alert('Payment added successfully!');
        },
        (error) => {
          console.error('Error adding card:', error);
          alert('Failed to add card. Please try again.');
        }
      );
    }

  ngOnInit(): void {
    // Subscribe to the logged-in user observable
    this.userService.loggedInUser$.subscribe((user) => {
      this.loggedInUser = user;

      // Fetch payment info only if the user is logged in
      if (this.loggedInUser) {
        this.paymentService.getPaymentInfo(this.loggedInUser.user_id).subscribe(
          (paymentInfo) => {
            if (paymentInfo) {
              this.paymentInfo = paymentInfo; // Assign the fetched payment info
            } else {
              this.paymentInfo = null; // No payment info found
            }
          },
          (error) => {
            console.error('Error fetching payment info:', error);
            this.paymentInfo = null;
          }
        );
      }
    });
  }
  


  showDialog(): void {
    this.visible = true;
  }
  // Method to hide the dialog (optional, can also use inline binding)
  hideDialog(): void {
    this.visible = false;
  }
  close(): void {
    this.visible = false;
    this.closeDialog.emit(); // Notify the parent component
  }
    
  // Reserve the car
  reserveCar(): void {
    if (!this.carData || !this.loggedInUser) {
      alert('Car data or user data is missing!');
      return;
    }

    // Ensure payment info exists (use a local const so TypeScript can narrow the type)
    const paymentInfo = this.paymentInfo;
    if (!paymentInfo) {
      alert('No payment information on file. Please add payment info before reserving.');
      return;
    }
    // Parse the dates into the desired format (YYYY-MM-DD)
    const startDate = this.dates[0] instanceof Date ? this.dates[0].toISOString().slice(0, 10) : null;
    const returnDate = this.dates[1] instanceof Date ? this.dates[1].toISOString().slice(0, 10) : null;

    if (!startDate || !returnDate) {
      alert('Invalid dates selected!');
      return;
    }
    // Create the rent-out object
    const rentOut: RentOuts = {
      rental_id: 0, // Auto-generated by the backend
      start_mileage: this.carData.miles,
      return_mileage: 0, // Set to 0 initially
      start_date: startDate, // Current date
      return_date: returnDate, // To be set later
      VIN: this.carData.VIN,
      user_id: this.loggedInUser.user_id,
      pickup_location_id: this.pickUpLocationId!,
      dropoff_location_id: this.dropOffLocationId!,
      payment_id: paymentInfo.payment_id,
    };
    
    // Call the addRental() method to create the rent-out
    this.rentalService.addRental(rentOut).subscribe(
      (response) => {
        console.log('Car reserved successfully:', response);
        alert('Car reserved successfully!');
        this.visible = false; // Close the dialog
      },
      (error) => {
        console.error('Error reserving car:', error);
        alert('Failed to reserve the car. Please try again.');
      }
    );
  }
  
  // Delete a car by VIN
  deleteCard(): void {
    if (!this.paymentInfo?.payment_id) {
      alert('Please enter a VIN to delete the car.');
      return;
    }

    this.paymentService.deletePaymentInfo(this.paymentInfo.payment_id).subscribe(
      (response) => {
        console.log('Card deleted successfully:', response);
        alert('Deleted card');
      },
      (error) => {
        console.error('Error deleting card:', error);
        alert('Failed to delete card');
      }
    );
  }
}
